version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - internal

  app:
    build: ./
    depends_on:
      - "rabbitmq"
    ports:
      - "8080:8080"
    environment:
      - RABBIT_MQ_HOST=rabbitmq
    networks:
      - internal

networks:
  internal:
